import type { Metadata } from "next";
import Providers from "./providers";
import { ColorSchemeScript } from "@mantine/core";
import '@mantine/core/styles.css';

export const metadata: Metadata = {
  title: "Laundro App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
			<head>
        <ColorSchemeScript defaultColorScheme="auto"/>
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <Providers>
					{children}
				</Providers>
      </body>
    </html>
  );
}
