
CREATE TABLE StoreImages
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	StoreId INT NOT NULL,
	[Url] VARCHAR(255) NOT NULL,
	[ContentType] VARCHAR(255) NOT NULL,
	CreatedAt DATETIME2 DEFAULT SYSDATETIME(),
	IsActive BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_Store FOREIGN KEY (StoreId) REFERENCES Stores(Id)
)
GO;