CREATE TABLE ScriptVersion
(
	Hash VARCHAR(64) NOT NULL
)

CREATE TABLE Roles
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	SystemKey VARCHAR(100) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
)

CREATE TABLE Users
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Email VARCHAR(255) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
)

CREATE TABLE UserRoles
(
	UserId INT NOT NULL,
	RoleId INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_User FOREIGN KEY (UserId) REFERENCES Users(Id),
	CONSTRAINT FK_Role FOREIGN KEY (RoleId) REFERENCES Roles(Id)
)
CREATE UNIQUE  NONCLUSTERED INDEX IX_UserRoles_UserId_RoleId_IsActive
ON UserRoles (UserId, RoleId, IsActive);


CREATE TABLE Stores
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	OwnerId INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_Owner FOREIGN KEY (OwnerId) REFERENCES Users(Id)
)